### PR TITLE
Rewritten episode 1 to fit Spyder IDE instead of Jupyter

### PR DESCRIPTION
**Pull request by Ylja**
fixed some minor mistakes in the setup.md,
updated episode 1.

### CODE REVIEW

**Comment by c-martinez** [comment]
Two things:
 - Can you add a link on the index to the renamed lesson?
 - Perhaps you could replace your user name from `runfile('/home/ylja/.config/spyder-py3/temp.py', wdir='/home/ylja/.config/spyder-py3')` to something like `runfile('~/.config/spyder-py3/temp.py', wdir='~/.config/spyder-py3')` or `runfile('/home/<username>/.config/spyder-py3/temp.py', wdir='/home/<username>/.config/spyder-py3')`

Afterwards we can merge your PR.

**Comment by richyvk** [comment]
Weird thing with the setup. I installed Spyder via PIP and the command i have to run it is Spyder3 not Spyder?

**Comment by richyvk** [comment]
Made a few changes to the episode - happy to merge??

**Comment by c-martinez** [comment]
The `/home/ylja` is still there, but let's merge it now. If @Ylja prefers to delete the path, we can do it later.

**Comment by richyvk** [comment]
:thumbsup:

**Pull request merged**
