### PR TITLE
adding recipe card analogy about function defs

### PR DESCRIPTION
**Pull request by elliewix**
The fact that a function can be defined but the code not actually run trips up many beginners.  I'm adding an analogy that has worked in the past to clear that up.  Also, it meshes well with the recipe analogy later on in this episode.

### CODE REVIEW

**Comment by richyvk** [comment]
Wondering if there might be a better phrase than "learned and remembered"??

**Comment by elliewix** [comment]
Ya...I'm open to suggestions on that one.  This is one of the biggest tripping points for new students. That a function that has had its definition executed but not yet been called lives in this interstitial.  Where the recipe has been learned by python, but not yet attempted.

**Comment by c-martinez** [comment]
I would say "a new function has been added to Python's catalogue". Probably we can keep the recipe analogy.

**Comment by richyvk** [comment]
evaluated and stored?
read and stored?

**Comment by elliewix** [comment]
I'd go with "read and stored" because evaluated has the connotation of being executed.

**Comment by c-martinez** [comment]
Let's go with "read and stored" then. @elliewix -- can you add a new commit with the change? Then we can merge this PR?

**Comment by elliewix** [comment]
OK, I edited my patch (I think). Can you take a look?

**Pull request merged**
